### ISSUE TITLE
COMPAT: imp module was deleted in python 3.12

### ISSUE THREAD

**Issue by uihyunglee** [surfhawk/sl4p#2]
### Describe the issue:  

I tried to import sl4p from python 3.12, but an error occurred. In python 3.12 and later version, the imp module required for that feature seems to have been deleted.  

### Reproduce the code example:  

```python
from sl4p import *  # in python >= 3.12
```  

### Error message:  

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~\Lib\site-packages\sl4p\__init__.py", line 2, in <module>
    from .src.api import sl4p, sl4p_try, sl4p_try_exit, sl4p_time, register_post_exception_terminationf
  File "~\Lib\site-packages\sl4p\src\api.py", line 3, in <module>
    from .context import sl4p
  File "~\Lib\site-packages\sl4p\src\context.py", line 7, in <module>
    from .config import Sl4pConfig
  File "~\Lib\site-packages\sl4p\src\config.py", line 5, in <module>
    from imp import reload
ModuleNotFoundError: No module named 'imp'
```  

### Python and sl4p Versions:  

```
python: 3.12.2
sl4p: 1.4.3
```

**Comment by surfhawk** [comment]
Thanks for your report.

The usage of the module `imp` has been replaced with `importlib` since sl4p version 1.4.4
Internally, the `imp` module will only be used if Python <= 3.1, otherwise, `importlib` will be used.

Please checkout the new version of sl4p and confirm if the issue has been resolved.
I will close this issue if confimed. :)

@uihyunglee

**Comment by uihyunglee** [comment]
Thank you for the update.

I've tested the new version of sl4p, and I'm happy to confirm that the issue has been resolved with the switch to importlib. Everything is working smoothly now.

I appreciate your support and the quick response!

@surfhawk
